### ISSUE TITLE
Quic

### ISSUE THREAD

**Issue by Fossil01** [Paul-Reed/cloudflare-ufw#12]
HTTP/3 or QUIC requires UDP to be open. Might be useful removing the `proto tcp` from port 443 rules.

**Comment by Paul-Reed** [comment]
Thanks @Fossil01 
I'm not sure about changing all of the 443 rules as so many frameworks still do not support QUIC (and therefore HTTP/3), such as ExpressJS, websockets, etc.
But I've updated the port 443 example, and made it clearer that it supports UDP, so users have now a choice.

**Comment by Paul-Reed** [comment]
Closed via https://github.com/Paul-Reed/cloudflare-ufw/commit/de5ffc544eaf5e7d89bfc69cb0182c6d07cd0b59
