### ISSUE TITLE
ERROR: Invalid token 'comment'

### ISSUE THREAD

**Issue by kagurareina** [Paul-Reed/cloudflare-ufw#6]
:~/cloudflare-ufw# ./cloudflare-ufw.sh
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'
ERROR: Invalid token 'comment'

**Comment by Paul-Reed** [comment]
As described in the readme, run the script using Elevated Privileges and not as a user.
`sudo /your/path/cloudflare-ufw/./cloudflare-ufw.sh`

Have you made any edits to the script? try deleting the folder `cloudflare-ufw` and re-installing it by cloning the repo again.

**Comment by Paul-Reed** [comment]
No further update from OP
